include: package:lints/recommended.yaml
linter:
  rules:
    - always_put_required_named_parameters_first
    # - always_specify_types
    - always_use_package_imports
    - annotate_overrides
    - annotate_redeclares
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_final_parameters
    - avoid_function_literals_in_foreach_calls
    - avoid_futureor_void
    - avoid_multiple_declarations_per_line
    - avoid_print
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - avoid_web_libraries_in_flutter
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - collection_methods_unrelated_type
    - combinators_ordering
    - conditional_uri_does_not_exist
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - dangling_library_doc_comments
    - depend_on_referenced_packages
    - deprecated_consistency
    - deprecated_member_use_from_same_package
    # - diagnostic_describe_all_properties
    - directives_ordering
    - discarded_futures
    - do_not_use_environment
    - document_ignores
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - eol_at_end_of_file
    - exhaustive_cases
    - file_names
    - flutter_style_todos
    - hash_and_equals
    - implementation_imports
    - implicit_call_tearoffs
    - implicit_reopen
    - invalid_case_patterns
    - leading_newlines_in_multiline_strings
    - library_annotations
    - library_names
    - library_prefixes
    - library_private_types_in_public_api
    - lines_longer_than_80_chars
    - literal_only_boolean_expressions
    - matching_super_parameters
    - missing_code_block_language_in_doc_comment
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_default_cases
    - no_duplicate_case_values
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - no_logic_in_create_state
    - no_runtimeType_toString
    - no_self_assignments
    - no_wildcard_variable_uses
    - null_check_on_nullable_type_parameter
    - null_closures
    - one_member_abstracts
    - package_names
    - prefer_asserts_in_initializer_lists
    - prefer_const_declarations
    - prefer_contains
    - prefer_expression_function_bodies
    - prefer_double_quotes 
    - prefer_final_fields
    - prefer_final_locals
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_void_to_null
    - recursive_getters
    - require_trailing_commas
    - slash_for_doc_comments
    - sort_pub_dependencies
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - specify_nonobvious_local_variable_types
    - specify_nonobvious_property_types
    - strict_top_level_inference
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_async
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_breaks
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_ignore
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unnecessary_to_list_in_spreads
    - unnecessary_underscores
    - unreachable_from_main
    - unrelated_type_equality_checks
    - use_build_context_synchronously
    - use_enums
    - use_is_even_rather_than_modulo
    - use_key_in_widget_constructors
    - use_rethrow_when_possible
    - use_string_buffers
    - valid_regexps

